name:                TreeDiagrams
version:             0.1.0.0
github:              "githubuser/TreeDiagrams"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2025 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TreeDiagrams#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams-core
- diagrams-lib 
- diagrams-contrib
- diagrams-svg
- prettyprinter
- recursion-schemes
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
# Syntax
  - OverloadedStrings
  - LambdaCase
  - PartialTypeSignatures
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - BangPatterns
 

  # Type
  - DataKinds
  - TypeFamilies
  - GADTs
  
  # Type-class
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses

  # Deriving 
  - DeriveGeneric
  - DeriveFunctor
  - DeriveFoldable
  - DeriveTraversable
  - TemplateHaskell
  
executables:
  TreeDiagrams-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TreeDiagrams

tests:
  TreeDiagrams-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TreeDiagrams
